# Generated by Django 6.0.2 on 2026-03-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingtemplateitem',
            name='template_category',
        ),
        migrations.RenameField(
            model_name='packingtemplateitem',
            old_name='sort_order',
            new_name='picked_quantity',
        ),
        migrations.RemoveField(
            model_name='packinglistitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='packingtemplateitem',
            name='name',
        ),
        migrations.AddField(
            model_name='packingtemplateitem',
            name='main_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='closet.itemcategorytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packingtemplateitem',
            name='sub_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='closet.itemcategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PackingTemplateCategory',
        ),
    ]
