# Generated by Django 6.0.2 on 2026-03-15 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0002_initial'),
        ('packing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripevent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='packing.trip'),
        ),
        migrations.AddField(
            model_name='trippackingitem',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='closet.itemcategorytype'),
        ),
        migrations.AddField(
            model_name='trippackingitem',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='closet.itemcategory'),
        ),
        migrations.AddField(
            model_name='trippackingitem',
            name='template_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packing.packingtemplateitem'),
        ),
        migrations.AddField(
            model_name='trippackingitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='packing.trip'),
        ),
        migrations.AddField(
            model_name='trippackingitemselection',
            name='closet_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_selections', to='closet.closetitem'),
        ),
        migrations.AddField(
            model_name='trippackingitemselection',
            name='packing_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='packing.trippackingitem'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packing.triptype'),
        ),
        migrations.AddField(
            model_name='packingtemplate',
            name='trip_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.triptype'),
        ),
    ]
