# Generated by Django 6.0.2 on 2026-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingtemplate',
            name='is_system',
            field=models.BooleanField(default=True),
        ),
    ]
