# Generated by Django 6.0.2 on 2026-03-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_remove_packingtemplateitem_template_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingtemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packing.packingtemplate'),
        ),
    ]
