# Generated by Django 6.0.2 on 2026-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_alter_trip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingtemplateitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
