# Generated by Django 6.0.2 on 2026-03-09 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_alter_packingtemplateitem_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingtemplateitem',
            name='picked_quantity',
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='picked_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='template_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packing.packingtemplateitem'),
        ),
        migrations.AlterField(
            model_name='packinglistitem',
            name='packing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packing.packinglist'),
        ),
    ]
