# Generated by Django 6.0.2 on 2026-03-10 00:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_remove_itemcategory_closet_item_user_id_e93c8a_idx_and_more'),
        ('packing', '0004_remove_packingtemplateitem_picked_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packinglistitem',
            name='packing_list',
        ),
        migrations.RemoveField(
            model_name='packinglistitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='packinglistitem',
            name='closet_item',
        ),
        migrations.RemoveField(
            model_name='packinglistitem',
            name='template_item',
        ),
        migrations.CreateModel(
            name='PackingClosetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete'), ('archived', 'Archived')], default='active', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('picked_quantity', models.IntegerField(default=0)),
                ('is_packed', models.BooleanField(default=False)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('is_custom_item', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='closet.itemcategory')),
                ('closet_item', models.ManyToManyField(blank=True, to='closet.closetitem')),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packing.packingtemplateitem')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='packing.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PackingList',
        ),
        migrations.DeleteModel(
            name='PackingListItem',
        ),
    ]
