# Generated by Django 6.0.2 on 2026-04-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_alter_packingtemplateitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippackingitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
