# Generated by Django 6.0.2 on 2026-03-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_remove_packinglistitem_packing_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingclosetitem',
            name='category',
        ),
    ]
