# Generated by Django 6.0.2 on 2026-04-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_alter_trippackingitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippackingitemselection',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
