# Generated by Django 6.0.2 on 2026-03-10 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_remove_closetitem_closet_clos_categor_427eca_idx_and_more'),
        ('packing', '0006_remove_packingclosetitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingtemplateitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packingtemplateitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_template_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Complete', 'Complete'), ('Past', 'Past'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('deadline', 'Deadline'), ('trip_start', 'Trip Start'), ('trip_end', 'Trip End'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='packing.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripPackingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete'), ('archived', 'Archived')], default='active', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('picked_quantity', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_packed', models.BooleanField(default=False)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('is_custom_item', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='closet.itemcategorytype')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='closet.itemcategory')),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packing.packingtemplateitem')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='packing.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripPackingItemSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('closet_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_selections', to='closet.closetitem')),
                ('packing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='packing.trippackingitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PackingClosetItem',
        ),
    ]
