# Generated by Django 6.0.2 on 2026-05-05 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_alter_trippackingitemselection_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingtemplate',
            name='season',
            field=models.CharField(blank=True, choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Rainy', 'Rainy'), ('Autumn', 'Autumn'), ('Late Autumn', 'Late Autumn'), ('Spring', 'Spring'), ('None', 'None')], default='Summer', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='packingtemplate',
            name='trip_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.triptype'),
        ),
    ]
