# Generated by Django 6.0.2 on 2026-03-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0007_packingtemplateitem_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingtemplate',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Rainy', 'Rainy'), ('Autumn', 'Autumn'), ('Late Autumn', 'Late Autumn'), ('Spring', 'Spring'), ('None', 'None')], default='Summer', max_length=20),
        ),
    ]
