# Generated by Django 6.0.2 on 2026-05-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0007_alter_packingtemplate_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingtemplate',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
