# Generated by Django 6.0.2 on 2026-05-08 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0008_alter_packingtemplate_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippackingitem',
            name='is_packed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='trippackingitem',
            name='is_required',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trippackingitem',
            name='picked_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trippackingitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trippackingitem',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='packing.trip'),
        ),
    ]
