# Generated by Django 6.0.2 on 2026-05-08 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('packing', '0009_alter_trippackingitem_is_packed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingtemplateitem',
            name='brand_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.brandcategory'),
        ),
        migrations.AddField(
            model_name='packingtemplateitem',
            name='show_shop_url',
            field=models.BooleanField(default=False),
        ),
    ]
