# Generated by Django 6.0.2 on 2026-05-09 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_alter_itemcategorytype_code'),
        ('packing', '0010_packingtemplateitem_brand_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingtemplateitem',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='closet.itemcategorytype'),
        ),
        migrations.CreateModel(
            name='PackingTemplateCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='packing.packingtemplate')),
            ],
            options={
                'verbose_name_plural': 'Packing Template Categories',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='packingtemplateitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='packing.packingtemplatecategory'),
        ),
    ]
