# Generated by Django 6.0.2 on 2026-05-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0011_alter_packingtemplateitem_main_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingtemplateitem',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='packingtemplateitem',
            name='sub_category',
        ),
    ]
