# Generated by Django 6.0.2 on 2026-05-09 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_alter_itemcategorytype_code'),
        ('packing', '0012_remove_packingtemplateitem_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingtemplateitem',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='closet.itemcategorytype'),
        ),
        migrations.AddField(
            model_name='packingtemplateitem',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='closet.itemcategory'),
        ),
    ]
