# Generated by Django 6.0.2 on 2026-05-12 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0014_remove_packingtemplateitem_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippackingitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_items', to='packing.packingtemplatecategory'),
        ),
    ]
