# Generated by Django 6.0.2 on 2026-05-22 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('packing', '0015_trippackingitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packingtemplate',
            options={'verbose_name': 'Camp', 'verbose_name_plural': 'Camps'},
        ),
        migrations.AlterModelOptions(
            name='packingtemplateitem',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='packingtemplate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Camp'),
        ),
        migrations.AlterField(
            model_name='packingtemplateitem',
            name='brand_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.brandcategory', verbose_name='Sentences'),
        ),
        migrations.AlterField(
            model_name='packingtemplateitem',
            name='show_shop_url',
            field=models.BooleanField(default=False, verbose_name='Shop Now Enable'),
        ),
    ]
