# Generated by Django 6.0.2 on 2026-05-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0016_alter_packingtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingtemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packing_templates/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='packingtemplate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Camp name'),
        ),
        migrations.AlterField(
            model_name='packingtemplate',
            name='trip_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.triptype', verbose_name='Camp Type'),
        ),
    ]
