# Generated by Django 6.0.2 on 2026-05-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0017_alter_packingtemplate_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Camper', 'verbose_name_plural': 'Campers'},
        ),
    ]
