# Generated by Django 6.0.2 on 2026-05-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0018_alter_trip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Camp Location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Camp Name'),
        ),
    ]
