from django.contrib import admin
from django.urls import path, reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from unfold.admin import ModelAdmin, TabularInline
from unfold.decorators import action, display
from unfold.views import UnfoldModelAdminViewMixin
import os
import logging
from packing.generate_template_ai import PackingListAI
from packing.models import (
    TripType, Trip,
    PackingTemplate, PackingTemplateItem, PackingTemplateCategory,
    TripPackingItem, TripPackingItemSelection, TripEvent
)


# @admin.register(TripType)
# class TripTypeAdmin(ModelAdmin):
#     list_display = ('name', 'code', 'created_at')
#     search_fields = ('name', 'code')
#     readonly_fields = ('created_at', 'updated_at')
#     exclude = ('deleted_at',)


class PackingTemplateItemInline(TabularInline):
    model = PackingTemplateItem
    extra = 1
    exclude = ('deleted_at',)
    tab = True
    show_count = True
    # raw_id_fields = ('category',)

    def formfield_for_foreignkey(self, db_field, request, **kwargs):
        if db_field.name == "category":
            import re
            match = re.search(r'packingtemplate/([^/]+)/change', request.path)
            if match:
                template_id = match.group(1)
                kwargs["queryset"] = PackingTemplateCategory.objects.filter(template_id=template_id)
            else:
                kwargs["queryset"] = PackingTemplateCategory.objects.none()
        return super().formfield_for_foreignkey(db_field, request, **kwargs)


class PackingTemplateCategoryInline(TabularInline):
    model = PackingTemplateCategory
    extra = 1
    exclude = ('deleted_at',)
    tab = True
    show_count = True


# @admin.register(PackingTemplateCategory)
# class PackingTemplateCategoryAdmin(ModelAdmin):
#     list_display = ('name', 'template', 'sort_order')
#     list_filter = ('template',)
#     search_fields = ('name', 'template__title')
#     readonly_fields = ('created_at', 'updated_at')
#     exclude = ('deleted_at',)


class UploadAIView(UnfoldModelAdminViewMixin, TemplateView):
    title = "Upload & Generate AI Packing Template"
    template_name = "admin/packing/packingtemplate/upload_ai.html"
    permission_required = ()

    def post(self, request, *args, **kwargs):
        uploaded_file = request.FILES.get('packing_file')
        if not uploaded_file:
            messages.error(request, "No file uploaded.")
            return self.get(request, *args, **kwargs)

        fs = FileSystemStorage()
        filename = fs.save(uploaded_file.name, uploaded_file)
        file_path = fs.path(filename)

        try:
            from django.conf import settings
            api_key = getattr(settings, 'OPENAI_API_KEY', None)
            
            extractor = PackingListAI(api_key=api_key)
            result = extractor.process_file(file_path)

            season_str = result.get('season') or 'None'
            season = 'None'
            for choice_val, choice_label in PackingTemplate.SEASON_CHOICES:
                if season_str.strip().lower() in [choice_val.lower(), choice_label.lower()]:
                    season = choice_val
                    break

            trip_type_str = result.get('trip_type')
            trip_type = None
            if trip_type_str:
                trip_type, _ = TripType.objects.get_or_create(
                    name=trip_type_str.strip().title(),
                    defaults={'code': trip_type_str.strip().lower().replace(' ', '_')}
                )

            template = PackingTemplate.objects.create(
                title=result.get('title') or f"AI Generated Template ({uploaded_file.name})",
                description=result.get('description') or f"Automatically generated by AI OCR & Vision from {uploaded_file.name}.",
                season=season,
                trip_type=trip_type,
                is_system=result.get('is_system', True)
            )

            for cat_idx, cat_data in enumerate(result.get('categories', [])):
                category = PackingTemplateCategory.objects.create(
                    template=template,
                    name=(cat_data.get('name') or "UNCATEGORIZED").strip().upper(),
                    sort_order=cat_data.get('sort_order') or cat_idx
                )
                for item_idx, item_data in enumerate(cat_data.get('items', [])):
                    PackingTemplateItem.objects.create(
                        template=template,
                        category=category,
                        title=item_data.get('title') or "Untitled Item",
                        quantity=item_data.get('quantity') or 0,
                        is_required=item_data.get('is_required', True),
                        note=item_data.get('note'),
                        sort_order=item_idx
                    )

            if os.path.exists(file_path):
                os.remove(file_path)

            messages.success(request, f"Successfully generated packing template: '{template.title}'!")
            
            change_url = reverse(
                "admin:packing_packingtemplate_change",
                args=[template.id]
            )
            return HttpResponseRedirect(change_url)

        except Exception as e:
            if os.path.exists(file_path):
                os.remove(file_path)
            
            logger = logging.getLogger("admin")
            logger.error("AI Packing Template Generation failed: %s", str(e), exc_info=True)
            messages.error(request, f"AI Extraction Failed: {str(e)}")
            return self.get(request, *args, **kwargs)


@admin.register(PackingTemplate)
class PackingTemplateAdmin(ModelAdmin):
    list_display = (
        'title',
        'trip_type',
        'season_badge',
        # 'system_badge',
        # 'status_badge',
        'created_at'
    )
    list_filter = (
        'trip_type',
        'season',
        'is_system',
        'is_active'
    )
    search_fields = ('title', 'description')
    readonly_fields = ('created_at', 'updated_at')
    exclude = ('deleted_at', 'sort_order')

    fieldsets = (
        ("General Information", {
            "fields": ("title", "trip_type", "season", "is_active"),
        }),
        ("Template Details & Media", {
            "fields": ("description", "image", "is_system"),
        }),
    )

    actions_list = ["upload_ai_button"]

    @action(
        description="Upload & Generate (AI)",
        icon="auto_awesome",
        url_path="upload-ai-action"
    )
    def upload_ai_button(self, request):
        return HttpResponseRedirect(reverse("admin:packing_packingtemplate_upload_ai"))

    def get_urls(self):
        urls = super().get_urls()
        custom_urls = [
            path(
                "upload-ai/",
                self.admin_site.admin_view(UploadAIView.as_view(model_admin=self)),
                name="packing_packingtemplate_upload_ai"
            ),
        ]
        return custom_urls + urls

    def changeform_view(self, request, object_id=None, form_url='', extra_context=None):
        if request.method == "POST" and request.POST.get("_save_custom") == "1":
            import json
            from django.db import transaction
            try:
                with transaction.atomic():
                    payload = json.loads(request.POST.get("payload"))
                    camp_name = request.POST.get("camp_name")
                    season = request.POST.get("season")
                    trip_type_id = request.POST.get("trip_type_id")
                    is_system = request.POST.get("is_system") == "1"
                    sort_order = int(request.POST.get("sort_order", 0))
                    description = request.POST.get("description")
                    
                    template = self.get_object(request, object_id) if object_id else None
                    is_new = False
                    if not template:
                        is_new = True
                        template = PackingTemplate.objects.create(
                            title=camp_name,
                            season=season,
                            trip_type=TripType.objects.filter(id=trip_type_id).first() if trip_type_id else None,
                            is_system=is_system,
                            sort_order=sort_order,
                            description=description,
                            is_active=True
                        )
                    else:
                        template.title = camp_name
                        template.season = season
                        
                        if trip_type_id:
                            template.trip_type = TripType.objects.filter(id=trip_type_id).first()
                        else:
                            template.trip_type = None
                            
                        template.is_system = is_system
                        template.sort_order = sort_order
                        template.description = description
                        template.save()

                    # Track existing categories and items to delete ones that are removed
                    existing_categories = {str(c.id): c for c in template.categories.all()} if not is_new else {}
                    existing_items = {str(i.id): i for i in template.items.all()} if not is_new else {}

                    kept_category_ids = set()
                    kept_item_ids = set()

                    # Save Categories
                    category_id_mapping = {} # Map UI temp IDs to real database UUIDs
                    for cat_idx, cat_data in enumerate(payload.get("categories", [])):
                        cat_id = cat_data.get("id")
                        cat_name = cat_data.get("name")
                        cat_sort = cat_data.get("sort_order", cat_idx)

                        if cat_id in existing_categories:
                            category = existing_categories[cat_id]
                            category.name = cat_name
                            category.sort_order = cat_sort
                            category.save()
                            kept_category_ids.add(cat_id)
                            category_id_mapping[cat_id] = category
                        else:
                            category = PackingTemplateCategory.objects.create(
                                template=template,
                                name=cat_name,
                                sort_order=cat_sort
                            )
                            category_id_mapping[cat_id] = category
                            kept_category_ids.add(str(category.id))

                    # Save Items
                    for item_idx, item_data in enumerate(payload.get("items", [])):
                        item_id = item_data.get("id")
                        cat_temp_id = item_data.get("category_id")
                        brand_category_id = item_data.get("brand_category_id")
                        title = item_data.get("title")
                        quantity = int(item_data.get("quantity", 0))
                        is_required = item_data.get("is_required", True)
                        show_shop_url = item_data.get("show_shop_url", False)
                        
                        # Store note, sentences, and url in the note field as a JSON string
                        note_payload = {
                            "note": item_data.get("note", ""),
                            "sentences": item_data.get("sentences", ""),
                            "url": item_data.get("url", "")
                        }
                        note_str = json.dumps(note_payload)

                        # Get the saved category object
                        category_obj = category_id_mapping.get(cat_temp_id)

                        from dashboard.models import BrandCategory
                        brand_cat_obj = BrandCategory.objects.filter(id=brand_category_id).first() if brand_category_id else None

                        if item_id in existing_items:
                            item = existing_items[item_id]
                            item.category = category_obj
                            item.brand_category = brand_cat_obj
                            item.title = title
                            item.quantity = quantity
                            item.is_required = is_required
                            item.show_shop_url = show_shop_url
                            item.note = note_str
                            item.sort_order = item_idx
                            item.save()
                            kept_item_ids.add(item_id)
                        else:
                            item = PackingTemplateItem.objects.create(
                                template=template,
                                category=category_obj,
                                brand_category=brand_cat_obj,
                                title=title,
                                quantity=quantity,
                                is_required=is_required,
                                show_shop_url=show_shop_url,
                                note=note_str,
                                sort_order=item_idx
                            )
                            kept_item_ids.add(str(item.id))

                    # Delete categories and items that were removed in the UI
                    for cat_id, cat_obj in existing_categories.items():
                        if cat_id not in kept_category_ids:
                            cat_obj.delete()

                    for item_id, item_obj in existing_items.items():
                        if item_id not in kept_item_ids:
                            item_obj.delete()

                    messages.success(
                        request, 
                        f"Successfully {'created' if is_new else 'updated'} camp packing list details for: '{template.title}'!"
                    )
                    
                    if is_new:
                        from django.urls import reverse
                        redirect_url = reverse("admin:packing_packingtemplate_change", args=[template.id])
                        return HttpResponseRedirect(redirect_url)
                    else:
                        return HttpResponseRedirect(request.path)

            except Exception as e:
                import logging
                logger = logging.getLogger("admin")
                logger.error("Failed to save custom packing list dashboard details: %s", str(e), exc_info=True)
                messages.error(request, f"Error saving packing list details: {str(e)}")
                return HttpResponseRedirect(request.path)

        extra_context = extra_context or {}
        extra_context["trip_types"] = TripType.objects.all()
        from dashboard.models import BrandCategory
        extra_context["brand_categories"] = BrandCategory.objects.all()
        return super().changeform_view(request, object_id, form_url, extra_context)



    @display(
        description="Season",
        label={
            "Summer": "warning",    # Warm yellow/orange
            "Winter": "info",       # Cool blue
            "Rainy": "danger",      # Red
            "Autumn": "success",    # Green
            "Late Autumn": "success",
            "Spring": "success",
            "None": "info",
        }
    )
    def season_badge(self, obj):
        return obj.season

    @display(
        description="Type",
        label={
            True: "info",      # Blue for System
            False: "warning",  # Orange for Custom
        }
    )
    def system_badge(self, obj):
        return "System" if obj.is_system else "Custom"

    @display(
        description="Status",
        label={
            True: "success",   # Green for Active
            False: "danger",   # Red for Inactive
        }
    )
    def status_badge(self, obj):
        return "Active" if obj.is_active else "Inactive"

    class Media:
        css = {
            'all': ('css/admin_custom.css',)
        }


# @admin.register(PackingTemplateItem)
# class PackingTemplateItemAdmin(ModelAdmin):
#     list_display = (
#         'template',
#         'category',
#         'brand_category',
#         'title',
#         'quantity',
#         'is_required',
#         'show_shop_url',
#         'sort_order'
#     )
#     list_filter = (
#         'template',
#         'brand_category',
#         'is_required',
#         'show_shop_url'
#     )
#     search_fields = (
#         'template__title', 'title', 'note',
#         'brand_category__name'
#     )
#     readonly_fields = ('created_at', 'updated_at')
#     exclude = ('deleted_at',)

#     # Display configuration
#     list_per_page = 10000
#     list_max_show_all = 10000
#     list_fullwidth = False

#     def formfield_for_foreignkey(self, db_field, request, **kwargs):
#         if db_field.name == "category":
#             import re
#             match = re.search(r'packingtemplateitem/([^/]+)/change', request.path)
#             if match:
#                 item_id = match.group(1)
#                 item = self.model.objects.filter(id=item_id).first()
#                 if item:
#                     kwargs["queryset"] = PackingTemplateCategory.objects.filter(template=item.template)
#         return super().formfield_for_foreignkey(db_field, request, **kwargs)


class TripPackingItemInline(TabularInline):
    model = TripPackingItem
    extra = 1
    raw_id_fields = (
        'category',
        'main_category',
        'sub_category',
        'template_item'
    )


class TripEventInline(TabularInline):
    model = TripEvent
    extra = 1


@admin.register(Trip)
class TripAdmin(ModelAdmin):
    list_display = (
        'user',
        'camp_name',
        'camp_type',
        'camp_status',
        'start_date',
        'end_date'
    )
    list_filter = (
        'trip_type',
        'status',
        'is_template_applied',
        'start_date'
    )
    search_fields = ('name', 'location', 'user__email')
    inlines = [TripPackingItemInline, TripEventInline]

    @display(description="Camp Name", ordering="name")
    def camp_name(self, obj):
        return obj.name

    @display(description="Camp Type", ordering="name")
    def camp_type(self, obj):
        return obj.trip_type.name

    @display(description="Camp Status", ordering="name")
    def camp_status(self, obj):
        return obj.status
    
    readonly_fields = ('created_at', 'updated_at')
    exclude = ('deleted_at',)


class TripPackingItemSelectionInline(TabularInline):
    model = TripPackingItemSelection
    extra = 1
    raw_id_fields = ('closet_item',)


# @admin.register(TripPackingItem)
# class TripPackingItemAdmin(ModelAdmin):
#     list_display = (
#         '__str__',
#         'trip',
#         'status',
#         'category',
#         'main_category',
#         'sub_category',
#         'title',
#         'quantity',
#         'picked_quantity',
#         'is_packed'
#     )
#     list_filter = (
#         'status',
#         'main_category',
#         'sub_category',
#         'is_packed',
#         'is_custom_item'
#     )
#     search_fields = (
#         'trip__name',
#         'title',
#         'note',
#         'sub_category__name'
#     )
#     inlines = [TripPackingItemSelectionInline]
#     raw_id_fields = (
#         'trip',
#         'category',
#         'main_category',
#         'sub_category',
#         'template_item'
#     )
#     readonly_fields = ('created_at', 'updated_at')
#     exclude = ('deleted_at',)


# @admin.register(TripPackingItemSelection)
# class TripPackingItemSelectionAdmin(ModelAdmin):
#     list_display = (
#         'packing_item',
#         'closet_item',
#         'quantity'
#     )
#     raw_id_fields = (
#         'packing_item',
#         'closet_item'
#     )
#     readonly_fields = ('created_at', 'updated_at')
#     exclude = ('deleted_at',)


# @admin.register(TripEvent)
# class TripEventAdmin(ModelAdmin):
#     list_display = (
#         'title',
#         'trip',
#         'event_type',
#         'date'
#     )
#     readonly_fields = ('created_at', 'updated_at')
#     exclude = ('deleted_at',)
