# Generated by Django 6.0.2 on 2026-05-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('apple', 'Apple')], default='email', max_length=50),
        ),
    ]
