# Generated by Django 6.0.2 on 2026-03-09 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemcategory',
            name='closet_item_user_id_e93c8a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('name', 'type')},
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='user',
        ),
    ]
