# Generated by Django 6.0.2 on 2026-03-15 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='closetitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='closetitem',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closet_items', to='closet.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='closet.itemcategorytype'),
        ),
        migrations.AddField(
            model_name='closetitem',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closet_items_main', to='closet.itemcategorytype'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['type'], name='closet_item_type_id_51248c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('user', 'name', 'type')},
        ),
        migrations.AddIndex(
            model_name='closetitem',
            index=models.Index(fields=['user'], name='closet_clos_user_id_0fdf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='closetitem',
            index=models.Index(fields=['sub_category'], name='closet_clos_sub_cat_916691_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='closetitem',
            unique_together={('user', 'name')},
        ),
    ]
