# Generated by Django 6.0.2 on 2026-03-10 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_remove_itemcategory_closet_item_user_id_e93c8a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='closetitem',
            name='closet_clos_categor_427eca_idx',
        ),
        migrations.RenameField(
            model_name='closetitem',
            old_name='ai_detected',
            new_name='is_favorite',
        ),
        migrations.RenameField(
            model_name='closetitem',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='closetitem',
            old_name='category',
            new_name='sub_category',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='users',
        ),
        migrations.AddField(
            model_name='closetitem',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='closetitem',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closet_items_main', to='closet.itemcategorytype'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='closetitem',
            index=models.Index(fields=['sub_category'], name='closet_clos_sub_cat_916691_idx'),
        ),
    ]
