# Generated by Django 6.0.2 on 2026-03-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_alter_closetitem_color'),
        ('closet', '0003_fix_color_json_field'),
    ]

    operations = [
    ]
