# Generated by Django 6.0.2 on 2026-03-10 21:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_remove_closetitem_closet_clos_categor_427eca_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('user', 'name', 'type')},
        ),
    ]
