# Generated by Django 6.0.2 on 2026-05-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_merge_20260329_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategorytype',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
