# Generated by Django 6.0.2 on 2026-03-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_alter_itemcategory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='closetitem',
            unique_together=set(),
        ),
    ]
