# Generated by Django 6.0.2 on 2026-05-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_alter_itemcategorytype_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='closetitem',
            unique_together=set(),
        ),
    ]
