# Generated by Django 6.0.2 on 2026-03-13 23:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_alter_closetitem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='closetitem',
            unique_together={('user', 'name')},
        ),
    ]
