# Generated by Django 6.0.2 on 2026-05-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0006_alter_closetitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closetitem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
