# Generated by Django 6.0.2 on 2026-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_communities_value',
            field=models.CharField(blank=True, default='+0K', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_downloads_value',
            field=models.CharField(blank=True, default='+0M', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_members_value',
            field=models.CharField(blank=True, default='+0M', max_length=50),
        ),
    ]
