# Generated by Django 6.0.2 on 2026-04-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_siteconfiguration_stat_communities_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='feature_1_description',
            field=models.TextField(blank=True, default='Snap a photo of any item. Our AI automatically detects the type, size, and brand to build your inventory in seconds.', verbose_name='Feature 1 Description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='feature_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Feature 1 Image'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='feature_1_title',
            field=models.CharField(blank=True, default='Smart Closet Scanner', max_length=255, verbose_name='Feature 1 Title'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='feature_2_description',
            field=models.TextField(blank=True, default="Seamlessly switch between children's profiles. Track\nwhat's in the closet for Leo and what's ready for Ava\nin one tap.", verbose_name='Feature 2 Description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='feature_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Feature 2 Image'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='feature_2_title',
            field=models.CharField(blank=True, default='Family Accounts', max_length=255, verbose_name='Feature 2 Title'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='features_section_title',
            field=models.CharField(blank=True, default='Features', max_length=255, verbose_name='Features Section Main Title'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_description',
            field=models.TextField(default='Organize camp gear, travel essentials, and closet\ninventory with invisible AI. Built for busy parents\nwho need simplicity, not another complex tool.', help_text='The text under the title. Use Enter for new lines.', verbose_name='Hero Description Text'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_desktop_image',
            field=models.ImageField(blank=True, help_text='The app preview image on desktop screens.', null=True, upload_to='site_images/', verbose_name='Hero Desktop Image'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_mobile_frame_image',
            field=models.ImageField(blank=True, help_text='The mobile phone frame image.', null=True, upload_to='site_images/', verbose_name='Hero Mobile App Preview Image'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_subtitle_blue',
            field=models.CharField(default='for the whole family.', help_text='The blue highlighted text next to/below the title.', max_length=255, verbose_name='Hero Highlighted Subtitle'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(default='Stress-free packing', help_text='The main heading text.', max_length=255, verbose_name='Hero Main Title'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='packing_section_description',
            field=models.TextField(blank=True, default='Smart lists that update based on weather, location. Never forget a\ntoothbrush (or a rain coat) again.', verbose_name='Packing Section Description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='packing_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Packing Section Image'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='packing_section_title',
            field=models.CharField(blank=True, default='Dynamic Packing Lists', max_length=255, verbose_name='Packing Section Title'),
        ),
    ]
