# Generated by Django 6.0.2 on 2026-05-10 23:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_siteconfiguration_feature_1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE landing_page_contactmessage ALTER COLUMN id DROP IDENTITY IF EXISTS; ALTER TABLE landing_page_contactmessage ALTER COLUMN id DROP DEFAULT IF EXISTS;',
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql='ALTER TABLE landing_page_contactmessage ALTER COLUMN id TYPE uuid USING (md5(random()::text || clock_timestamp()::text)::uuid);',
            reverse_sql=''
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE landing_page_siteconfiguration ALTER COLUMN id DROP IDENTITY IF EXISTS; ALTER TABLE landing_page_siteconfiguration ALTER COLUMN id DROP DEFAULT IF EXISTS;',
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql="ALTER TABLE landing_page_siteconfiguration ALTER COLUMN id TYPE uuid USING '00000000-0000-0000-0000-000000000001'::uuid;",
            reverse_sql=''
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE landing_page_testimonial ALTER COLUMN id DROP IDENTITY IF EXISTS; ALTER TABLE landing_page_testimonial ALTER COLUMN id DROP DEFAULT IF EXISTS;',
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql='ALTER TABLE landing_page_testimonial ALTER COLUMN id TYPE uuid USING (md5(random()::text || clock_timestamp()::text)::uuid);',
            reverse_sql=''
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
