from django.urls import path
from closet.api.views import (
    ItemCategoryTypeListView,
    ItemCategoryListView,
    ItemCategoryCreateView,
    ClosetItemListView,
    ClosetItemDetailView,
    ClosetItemCreateView,
    ClosetItemUpdateView,
    ClosetItemDeleteView,
    ClosetItemToggleFavoriteView,
)

urlpatterns = [
    path(
        'category-types/',
        ItemCategoryTypeListView.as_view(),
        name='category_types'
    ),
    path(
        'categories/',
        ItemCategoryListView.as_view(),
        name='item_categories'
    ),
    path(
        'categories/create/',
        ItemCategoryCreateView.as_view(),
        name='item_categories_create'
    ),
    path(
        'items/',
        ClosetItemListView.as_view(),
        name='closet_items'
    ),
    path(
        'items/create/',
        ClosetItemCreateView.as_view(),
        name='closet_items_create'
    ),
    path(
        'items/<uuid:pk>/',
        ClosetItemDetailView.as_view(),
        name='closet_items_detail'
    ),
    path(
        'items/<uuid:pk>/update/',
        ClosetItemUpdateView.as_view(),
        name='closet_items_update'
    ),
    path(
        'items/<uuid:pk>/delete/',
        ClosetItemDeleteView.as_view(),
        name='closet_items_delete'
    ),
    path(
        'items/<uuid:pk>/toggle-favorite/',
        ClosetItemToggleFavoriteView.as_view(),
        name='closet_items_toggle_favorite'
    ),
]
