JAZZMIN_CONFIG = {
    "site_title": "Comper Closet Admin",
    "site_header": "Comper Closet",
    "site_brand": "Comper Closet",
    "site_logo": "images/logo1.png",
    "welcome_sign": "Welcome to the Comper Closet Admin Panel",
    "copyright": "Comper Closet",
    "search_model": ["auth.User"],
    "user_avatar": "profile_pic",
    "topmenu_links": [
        {
            "name": "Home",
            "url": "admin:index",
            "permissions": ["auth.view_user"]
        },
        {
            "model": "auth.User"
        },
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "users.User": "fas fa-user-friends",
        "users.OTP": "fas fa-key",
        "users.EmailVerification": "fas fa-envelope-open-text",
        "users.Notification": "fas fa-bell",
        "users.NotificationSetting": "fas fa-cog",
        "closet.ItemCategoryType": "fas fa-tags",
        "closet.ItemCategory": "fas fa-th-list",
        "closet.ClosetItem": "fas fa-tshirt",
        "packing.TripType": "fas fa-map-marked-alt",
        "packing.PackingTemplate": "fas fa-clipboard-list",
        "packing.PackingTemplateItem": "fas fa-briefcase",
        "packing.Trip": "fas fa-plane-departure",
        "packing.TripPackingItem": "fas fa-luggage-cart",
        "packing.TripPackingItemSelection": "fas fa-check-square",
        "packing.TripEvent": "fas fa-calendar-day",
        "landing_page.SiteConfiguration": "fas fa-cogs",
        "landing_page.ContactMessage": "fas fa-envelope",
        "landing_page.Testimonial": "fas fa-comment-dots",
    },
    "order_with_respect_to": [
        "users",
        "closet",
        "packing",
        "landing_page",
        "auth"
    ],
    "use_google_fonts_cdn": True,
    "custom_css": "css/admin_custom.css",
}

JAZZMIN_UI_TWEAKS_CONFIG = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_fixed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-light-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_revamp_treeview": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "default_theme_mode": "light",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}